ImageId: ami-07c589821f2b353aa
InstanceMap:
  r7a.xlarge: 3
InstanceRolesMap:
  r7a.xlarge: [ data, ingest, ml, cluster_manager ]
RegionInfo:
  KeyName: your-key-name-that-can-ssh-to-ec2
  RegionName: ap-northeast-1
SecurityGroupIds:
- sg-026e2b947aa17c6c5 (your security group id, with port 9200 9300 22 80 opened)
Tags:
- Key: Name
  Value: your-identifier
VolumeSize: 500
cluster_node_dir: opensearch-2.17.0
identifier: your-identifier
store_dir: __store__
released:
  url: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.17.0/latest/linux/x64/tar/dist/opensearch/opensearch-2.17.0-linux-x64.tar.gz
  name: opensearch-2.17.0-linux-x64.tar.gz
init_password: MyStrongPassword123.
